Added dwm files

diff --git a/configDwm b/configDwm
--- a/configDwm
+++ b/configDwm
@@ -1,10 +1,27 @@
 #!/bin/sh
 
+# Stop on errors
+set -e
 
 # Install prerequisites for Dynamic Window Manager (dwm)
 echo "Installing prerequisites for dwm..."
 sudo apt install -y libxext-dev libxcb1-dev libxcb-damage0-dev libxcb-dpms0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-randr0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-present-dev libxcb-glx0-dev libpixman-1-dev libdbus-1-dev libconfig-dev libgl-dev libegl-dev libpcre2-dev libevdev-dev uthash-dev libev-dev libx11-xcb-dev meson
 sudo apt install -y build-essential libx11-dev libxinerama-dev sharutils suckless-tools libxft-dev stterm curl
 
+# Installing other tools
+echo "Installing other necessary tools"
+sudo apt install -y picom feh acpi rofi
+
 echo "Installing dwm..."
 sudo apt install -y dwm
+
+echo "Copying necessary files"
+cp -r eww/ ~/.config/eww/
+cp -r picom/ ~/.config/picom/
+cp -r rofi/ ~/.config/rofi/
+cp -r dwm/ ~/.config/dwm/
+sudo cp -r dwm.desktop /usr/share/xsessions/dwm.desktop
+
+# Compile dwm files
+echo "Compiling dwm configuration"
+cd ~/.config/dwm/ && sudo make install
